@PORT = 3000
@HOST = http://localhost:{{PORT}}


###### AUTHOR ########

GET {{HOST}}/api/authors

###
GET {{HOST}}/api/authors/4

###
POST {{HOST}}/api/authors
Content-Type: application/json

{
    "name": "Antonio Martín Lagares",
    "email": "antonio.martin.lagares@gmail.com",
    "image": "antonio.png"
}

###
PUT {{HOST}}/api/authors/1
Content-Type: application/json

{
    "name": "Lara Martín Lagares",
    "email": "lara.martin.lagares@gmail.com",
    "image": "laramartin.png" 
}

###
DELETE {{HOST}}/api/authors/5



######### POST #############

GET {{HOST}}/api/posts

###
GET {{HOST}}/api/posts/25

###
GET {{HOST}}/api/posts/author/4


###
POST {{HOST}}/api/posts
Content-Type: application/json

{
    "idAuthor": 4,
    "title": "Vacaciones de verano en la playa",
    "description": "Existen muchas opciones para pasar el verano; montaña, playa, ciudad. La mayor parte de la poblaciónp prefiere la playa....",
    "date": "2024-05-30 11:05",
    "category": "Ocio"
}

###
PUT {{HOST}}/api/posts/6
Content-Type: application/json

{
    "idAuthor": 3,
    "title": "Vacaciones de verano en la playa",
    "description": "Existen muchas opciones para pasar el verano; montaña, playa, ciudad. La mayor parte de la poblaciónp prefiere la playa....",
    "date": "2024-05-30 11:05",
    "category":  "Ocio"
}

###
DELETE {{HOST}}/api/posts/23

