@PORT = 3000
@HOST = http://localhost:{{PORT}}


###### AUTHOR ########

GET {{HOST}}/api/authors

###
GET {{HOST}}/api/authors/4

###
POST {{HOST}}/api/authors
Content-Type: application/json

{
    "name": "Antonio López Ruíz",
    "email": "antonio.lopez.ruiz@gmail.com",
    "image": "fernando.png"
}

###
PUT {{HOST}}/api/authors/6
Content-Type: application/json

{
    "name": "Antonio López Cano",
    "email": "antonio.lopez.cano@gmail.com",
    "image": "antonio.png" 
}

###
DELETE {{HOST}}/api/authors/8



######### POST #############

GET {{HOST}}/api/posts

###
GET {{HOST}}/api/posts/10

###
GET {{HOST}}/api/posts/author/4


###
POST {{HOST}}/api/posts
Content-Type: application/json

{
    "idAuthor": 4,
    "title": "Cómo Comprar en Tiendas de Segunda Mano y Encontrar Tesoros Único",
    "description": "Comprar en tiendas de segunda mano es una excelente manera de encontrar piezas únicas y sostenibles. Con estos consejos, podrás descubrir verdaderos tesoros y renovar tu guardarropa de manera económica y ecológica. Ten Paciencia: La clave para encontrar buenas piezas en tiendas de segunda mano es tener paciencia. Tómate tu tiempo para revisar las estanterías y los percheros detenidamente. Conoce tus Medidas: Lleva contigo una cinta métrica y conoce tus medidas. Las tallas pueden variar según la marca y la época, así que es mejor asegurarse de que algo te quede bien. Busca Calidad: Fíjate en la calidad de las telas y las costuras. Busca piezas que estén en buen estado y que sean de materiales duraderos.",
    "date": "2024-01-28",
    "category": "Moda"
}

###
PUT {{HOST}}/api/posts/11
Content-Type: application/json

{
    "idAuthor": 6,
    "title": "Sin vacaciones de verano",
    "description": "Existen muchas opciones para pasar el verano; montaña, playa, ciudad. La mayor parte de la poblaciónp prefiere la playa....",
    "date": "2024-05-30 11:05",
    "category":  "Ocio"
}

###
DELETE {{HOST}}/api/posts/13

